---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/route.yaml

namespace: color-race-game-prod
nameSuffix:
  -prod

commonLabels:
  app.kubernetes.io/instance: color-race-game-prod
