---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-terminal
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
