---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-system-operatorgroup
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
    - gitlab-system
  upgradeStrategy: Default
