---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-community-operator
  labels:
    operators.coreos.com/grafana-operator.grafana-community: ""
    operators.coreos.com/grafana-operator.grafana-community-operator: ""
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
