---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/namespace.yaml
  - resources/operatorgroup.yaml
  - resources/subscription.yaml

namespace: grafana-community-operator
